# Coursework 4

## Task 1

In [79]:
import numpy as np


def compute_polynomial_basis(vector, degree):
    output = list()
    for scalar in vector:
        row = list()
        for level in range(degree+1):
            row.append(scalar**level)
        output.append(row)
    output = (np.matrix(output))
#     print(output)
    return output


if __name__ == "__main__":
    input_ = np.array([1,2,3])
    degree = 2
    print(compute_polynomial_basis(input_, degree))

[[1 1 1]
 [1 2 4]
 [1 3 9]]


## Task 2

In [44]:
def generate_equidistant_input(s):
    X = np.linspace(0, 1, num=s)
    return X


if __name__ == "__main__":
    print(generate_equidistant_input(10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Task 3

In [47]:
input_vector = generate_equidistant_input(10)
output_degree_one = compute_polynomial_basis(input_vector, 1)
output_degree_three = compute_polynomial_basis(input_vector, 3)

[[1.         0.        ]
 [1.         0.11111111]
 [1.         0.22222222]
 [1.         0.33333333]
 [1.         0.44444444]
 [1.         0.55555556]
 [1.         0.66666667]
 [1.         0.77777778]
 [1.         0.88888889]
 [1.         1.        ]]
[[1.         0.         0.         0.        ]
 [1.         0.11111111 0.01234568 0.00137174]
 [1.         0.22222222 0.04938272 0.01097394]
 [1.         0.33333333 0.11111111 0.03703704]
 [1.         0.44444444 0.19753086 0.0877915 ]
 [1.         0.55555556 0.30864198 0.17146776]
 [1.         0.66666667 0.44444444 0.2962963 ]
 [1.         0.77777778 0.60493827 0.47050754]
 [1.         0.88888889 0.79012346 0.70233196]
 [1.         1.         1.         1.        ]]


## Task 4
Apply your matrices to the weights 
w1 = 2/5 −4/5
and w3 = 0 32/3 −32 64/3
from Coursework 2 and store your results in arrays y1 and y3. Visualise your results with tools from the Matplotlib-library


### Manual Solution

In [111]:
def apply_weights_to_matrice(matrix, weights):
    Xw = list()
    number_of_rows = matrix.shape[0]
    number_of_cols = matrix.shape[1]
    for row in range(number_of_rows):
        current_row = list()
        for col in range(number_of_cols):
            current_row.append(matrix.item(row, col) * weights[col])
        Xw.append(sum(current_row))
    return np.matrix(Xw)
    


if __name__ == "__main__":
    output_degree_one = compute_polynomial_basis(input_vector, 1)
    w1 = [2/5, -4/5]
    print( apply_weights_to_matrice(output_degree_one, w1))
    
    
    
    output_degree_three = compute_polynomial_basis(input_vector, 3)
    w3 = [0, 32/3, -32, 64/3]
    print( apply_weights_to_matrice(output_degree_three, w3))

[[ 0.4         0.31111111  0.22222222  0.13333333  0.04444444 -0.04444444
  -0.13333333 -0.22222222 -0.31111111 -0.4       ]]
[[ 0.00000000e+00  8.19387289e-01  1.02423411e+00  7.90123457e-01
   2.92638317e-01 -2.92638317e-01 -7.90123457e-01 -1.02423411e+00
  -8.19387289e-01 -3.55271368e-15]]


### Solution with Numpy Function

In [110]:
def apply_weights_to_matrice(matrix, weights):
    Xw = np.dot(matrix, weights)
    return Xw


if __name__ == "__main__":
    output_degree_one = compute_polynomial_basis(input_vector, 1)
    w1 = ((2/5, -4/5))
    print(apply_weights_to_matrice(output_degree_one, w1))

    output_degree_three = compute_polynomial_basis(input_vector, 3)
    w3 = np.array((0, 32/3, -32, 64/3))
    print( apply_weights_to_matrice(output_degree_three, w3))

[[ 0.4         0.31111111  0.22222222  0.13333333  0.04444444 -0.04444444
  -0.13333333 -0.22222222 -0.31111111 -0.4       ]]
[[ 0.00000000e+00  8.19387289e-01  1.02423411e+00  7.90123457e-01
   2.92638317e-01 -2.92638317e-01 -7.90123457e-01 -1.02423411e+00
  -8.19387289e-01 -3.55271368e-15]]


## Task 5
Write a function *regression* that takes two arguments *data matrix* and *data samples*, which computes and returns the solution $\hat{w}$ of the normal equation $Φ(X)^TΦ(X)\hat{w} = Φ(X)^Ty$.

Here $Φ(X)$ is the mathematical representation of data matrix and $y$ is the mathematical representation of data samples. 

Hint: make us of NumPy’s function linalg.solv

In [155]:
def regression(data_matrix, data_samples):
    data_matrix_tranposed = data_matrix.transpose()
    dot_product_left = np.dot(data_matrix_tranposed, data_matrix)
    dot_product_right = np.dot(data_matrix_tranposed, data_samples)
    
    # squeeze matrix into a numpy array as linalg.solve requires this format.
    right_side = np.squeeze(np.asarray(dot_product_right))
    return np.linalg.solve(dot_product_left, right_side)

    
if __name__ == "__main__":  
    data_samples = np.array([2,2,2])
    data_matrix = np.matrix([[1,-1],[1, 0],[1,-1]])
    print(regression(data_matrix, data_samples))

[2. 0.]
